name: Generate Static Site

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull requests to main branch
  pull_request:
    branches: [ main ]
    
  # Run on schedule - once a day at midnight UTC
  schedule:
    - cron: '0 0 * * *'
    
  # Allow manual triggers
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install streamlit pandas numpy plotly prophet scikit-learn ta tensorflow yfinance
        pip install selenium beautifulsoup4 webdriver-manager requests
        
    - name: Install Chrome for Selenium
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Generate static site
      run: |
        python static_site_generator.py
        
    - name: Copy custom static assets
      run: |
        # Copy 404 page if it doesn't already exist in the build directory
        if [ -f static_assets/404.html ] && [ ! -f build/404.html ]; then
          cp static_assets/404.html build/404.html
        fi
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages
